// <copyright file="GlobalSuppressions.cs" company="SIO">
// Copyright (c) SIO. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1642:Constructor summary documentation must begin with standard text", Justification = "<En attente>", Scope = "member", Target = "~M:ProjetOxf.Saisie.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1642:Constructor summary documentation must begin with standard text", Justification = "<En attente>", Scope = "member", Target = "~M:ProjetOxf.PrisePhoto.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1642:Constructor summary documentation must begin with standard text", Justification = "<En attente>", Scope = "member", Target = "~M:ProjetOxford.PersonneDejaInscriteException.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1642:Constructor summary documentation must begin with standard text", Justification = "<En attente>", Scope = "member", Target = "~M:ProjetOxford.PersonneDejaInscriteException.#ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1642:Constructor summary documentation must begin with standard text", Justification = "<En attente>", Scope = "member", Target = "~M:ProjetOxford.User.#ctor(System.String,System.String,System.DateTime,System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxford.User.Prenom")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxford.User.Nom")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxford.User.DateDeNaissance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxford.User.Email")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxford.User.Sexe")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxford.User.Type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxford.User.Code")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxf.Saisie.Photo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxf.Saisie.PrisEnPhoto")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxf.Saisie.FaceIdPersistent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation must match accessors", Justification = "<En attente>", Scope = "member", Target = "~P:ProjetOxf.Saisie.FaceIdTemp")]